---
title: "Resume Names Decision Tree Model"
author: "Ana Imam"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

### Read and Clean Data
```{r}
resumeNames <- read.csv("ResumeNames.csv", stringsAsFactors = TRUE)

resumeNames$X <- NULL

resumeNames <- as.data.frame(model.matrix(~. -1, resumeNames))

resumeNames$callyes <- as.factor(resumeNames$callyes)

library(janitor)

resumeNames <- clean_names(resumeNames)

summary(resumeNames)
```

### Create Train and Test Sets
```{r}
library(caret)
test_rows <- sample(1:nrow(resumeNames), nrow(resumeNames) * .7)

namesTrain <- (resumeNames[-test_rows, ])
upSampleTrain <- upSample(x=namesTrain, y = as.factor(namesTrain$callyes))


namesTest <- (resumeNames[test_rows, ])
upSampleTest <- upSample(x=namesTest, y = namesTest$call)
```

### Build a Model for Decision Tree Train Data
```{r}
library(C50)

namesModel <- C5.0(callyes ~ ., data = upSampleTrain)

str(upSampleTrain)

summary(upSampleTrain)

summary(namesModel)

plot(namesModel)
```

### Predict the Test Data
```{r}
CallPrediction <- predict(namesModel, upSampleTest)

library(gmodels)
CrossTable(upSampleTest$call, CallPrediction)

library(caret)

namesMatrix1 <- confusionMatrix(data = CallPrediction, reference = upSampleTest$callyes)
namesMatrix1

```


### Improved Model
```{r}

improvedNamesModel <- C5.0(callyes ~ ethnicitycauc + citychicago + jobs + experience + honorsyes + holesyes + emailyes + specialyes + collegeyes + equalyes + reqeducyes + reqcompyes + reqorgyes + industryfinance_insurance_real_estate + industryhealth_education_social_services + industrymanufacturing + industrytrade + industrytransport_communication + industryunknown , data = upSampleTrain)
str(upSampleTrain)

CallPrediction2 <- predict(improvedNamesModel, upSampleTest)

library(gmodels)
CrossTable(upSampleTest$call, CallPrediction2)


namesMatrix2 <- confusionMatrix(data = CallPrediction2, reference = upSampleTest$callyes)
namesMatrix2

```





