---
title: "Project#3: Prediction"
author: "Group 1"
date: "3/29/2021"
output: html_document
---

```{r}
resume <- read.csv("ResumeNames.csv", stringsAsFactors = TRUE)
library(class)
library(caret)
library(gmodels)
library(lmtest)
library(aod)
library(VGAM)
library(neuralnet)
library(e1071)
library(C50)
resume$name <- NULL
resume$X <- NULL
resume$minimum <- as.integer(resume$minimum)
str(resume)
```



## KNN Model
```{r}
## Make all factors dummy variables
resumemm <- as.data.frame(model.matrix(~.-1, resume))
str(resumemm)
```
```{r}
# Randomize the rows in the data (shuffling the rows)
set.seed(123)
res_random <- resumemm[sample(nrow(resumemm)),]
# #Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
# # we are going to normalize everything 
resume_norm <- as.data.frame(lapply(res_random, normalize))
##resume_z <- as.data.frame(scale(res_random[-1]))
```

```{r}
## Train and test sets for KNN
testrows <- sample(1:nrow(resume_norm), 0.3*nrow(resume_norm))
resume_train <- resume_norm[-testrows,-match("callyes",names(resume_norm))]
resume_test <- resume_norm[testrows, -match("callyes",names(resume_norm))]

## Train and test sets for other models
resume_train_2 <- resume_norm[-testrows,]
resume_test_2 <- resume_norm[testrows,]

#Now the response (aka Labels) - only the callyes column
res_train_labels <- resume_norm[-testrows, "callyes"]
res_test_labels <- resume_norm[testrows, "callyes"]
```

```{r}
library(class)
knum <- sqrt(nrow(resume_train))


knn_pred <- knn(train = resume_train, test = resume_test, cl = res_train_labels, k=knum)
#summary(resume_train)
```
```{r}
library(gmodels)
CrossTable(x = res_test_labels, y = knn_pred, 
           prop.chisq=FALSE)
caret::confusionMatrix(data = as.factor(knn_pred), reference = as.factor(res_test_labels))
```
## Logistic Regression
```{r}
## Train and test sets without dummy variables and normalization
testrows_2 <- sample(1:nrow(resume), 0.3*nrow(resume))
resume_test_3 <- resume[testrows, ]
lm1 <- glm(call ~ ., data = resume, family = "binomial")
steplm1 <- step(lm1)
summary(steplm1)
log2pred <- ifelse(predict(steplm1, newdata = resume_test_3, type = "response") > 0.2, 1, 0)
log2pred <- as.factor(log2pred)
#Check Predictions
CrossTable(x = res_test_labels, y = log2pred, 
           prop.chisq=FALSE)
confusionMatrix(as.factor(log2pred), as.factor(res_test_labels))
```

# ANN Model
```{r}
ANN_model1 <- neuralnet(callyes ~ . , data = resume_train_2, hidden = 1)

ANN_modelresults <- compute(ANN_model1, resume_test_2)
ANN_pred <- ANN_modelresults$net.result
resume_test_2$ANN_preds <- as.numeric(ifelse(ANN_pred > 0.20, 1, 0))

confusionMatrix(data = as.factor(resume_test_2$ANN_preds), reference = as.factor(resume_test_2$callyes), positive = '1')

str(resume_train_2)

ANN_model2 <- neuralnet(callyes ~ ethnicitycauc + citychicago + jobs + experience + honorsyes + holesyes + emailyes + specialyes + collegeyes + equalyes + reqeducyes + reqcompyes + reqorgyes + industryfinance.insurance.real.estate + industryhealth.education.social.services + industrymanufacturing + industrytrade + industrytransport.communication + industryunknown , data = resume_train_2, hidden = 1)

ANN_model2results <- compute(ANN_model2, resume_test_2)
ANN_pred2 <- ANN_model2results$net.result
resume_test_2$ANN_preds <- as.numeric(ifelse(ANN_pred2 > 0.20, 1, 0))

confusionMatrix(data = as.factor(resume_test_2$ANN_preds), reference = as.factor(resume_test_2$callyes), positive = '1')
```
# Decision Tree Model
```{r}
namesModel <- C5.0(as.factor(callyes) ~ ., data = resume_train_2)
summary(namesModel)

plot(namesModel)
#Predict test data
CallPrediction <- predict(namesModel, resume_test_2)
CrossTable(res_test_labels, CallPrediction)
confusionMatrix(data = as.factor(CallPrediction), reference = as.factor(res_test_labels))

#Improved Model
improvedNamesModel <- C5.0(as.factor(callyes) ~ ethnicitycauc + citychicago + jobs + experience + honorsyes + holesyes + emailyes + specialyes + collegeyes + equalyes + reqeducyes + reqcompyes + reqorgyes + industryfinance.insurance.real.estate + industryhealth.education.social.services + industrymanufacturing + industrytrade + industrytransport.communication + industryunknown , data = resume_test_2)

CallPrediction2 <- predict(improvedNamesModel, resume_test_2)

CrossTable(res_test_labels, CallPrediction2)

confusionMatrix(data = as.factor(CallPrediction2), reference = as.factor(res_test_labels))

```
# Data Frame with Predictions
```{r}
comb_pred <- data.frame(knn2 = knn_pred, log2 = log2pred, ann2 = ANN_pred2, dec_tree = CallPrediction2, callyes = res_test_labels)

test_rows_3 <- sample(1:nrow(comb_pred),0.3*nrow(comb_pred))
resume_test_4 <- comb_pred[test_rows_3,]
resume_train_4 <- comb_pred[-test_rows_3,]
comb_train_labels <- comb_pred[-test_rows_3, "callyes"]
comb_test_labels <- comb_pred[test_rows_3, "callyes"]
tree_model_2 <- C5.0(as.factor(callyes) ~ knn2 + log2 + ann2 + dec_tree, data = resume_train_4)
tree_pred_2 <- predict(tree_model_2, resume_test_4)

caret::confusionMatrix(data = as.factor(tree_pred_2), reference = as.factor(comb_test_labels))
```

