---
title: "Project3 Logistic Regression"
author: "Jihan"
date: "3/29/2021"
output: html_document
---

```{r include=FALSE}
# Necessary packages
library(tidyverse)
library(class)
library(caret)
library(gmodels)
library(lmtest)
library(aod)
library(VGAM)
library(e1071)
```

Reading + cleaning data:
```{r}
resume <- read.csv("ResumeNames.csv", stringsAsFactors = TRUE)
resume$name <- NULL
resume$X <- NULL
resume$minimum <- as.integer(resume$minimum)
str(resume)
```

### Logistic Regression Model

Model 1: all variables
```{r}
log1 <- glm(call ~ ., data = resume, family = "binomial")
summary(log1)
```

```{r include=FALSE}
# Filtering out insignificant variables using step function
log2 <- step(log1)
```

**Model 2**: only significant variables (from step function)
```{r}
summary(log2)
```

**Prediction**

Creating Test and Train data sets (with 30:70 split)
```{r}
set.seed(12345)
testrows <- sample(1:nrow(resume), 1461)
resumetest <- resume[testrows, ]
resumetrain <- resume[-testrows, ]
```

Confusion Matrix
```{r}
log2pred <- ifelse(predict(log2, newdata = resumetest, type = "response") > 0.2, "yes", "no")
log2pred <- as.factor(log2pred)
logmatrix <- confusionMatrix(log2pred, resumetest$call, positive="yes")
logmatrix
```




